### ISSUE TITLE
Link to tutorial results in 500 error.

### ISSUE THREAD

**Issue by dwbenjamin** [yast/yast-journalctl-tutorial#10]
The link on the yast-journalctl-tutorial, "http://yast.github.io/yast-journalctl-tutorial" results in `<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>`

**Comment by ancorgs** [comment]
As far as I know, the YaST github pages are actually served from openSUSE server, instead of using the github ones. I may be wrong, but I fear this error could be caused because when configuring all that we overlooked the fact that the yast.github.io page was not our only repository providing a github-page.

@lslezak do you know who can we ask to set this up correctly?

Meanwhile, I guess that forking the repository to a different organization could be a reasonable way to access the content of the tutorial. You could also use Jekyll locally, but that sounds more complicated).

**Comment by ancorgs** [comment]
> Meanwhile, I guess that forking the repository to a different organization could be a reasonable way to access the content of the tutorial.

It worked for me. You can use this link temporarily:
http://ancorgs.github.io/yast-journalctl-tutorial/
